apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
spec:
  type: NodePort  # Exposing the service using NodePort
  ports:
  - port: 8000  # External port
    targetPort: 8000  # Internal port where FastAPI app runs
  selector:
    app: ml-inference  # Matches the Deployment
